package helloworld;

public class toString {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		
		String gfg[]= {"are","you","a","geek"};
		StringBuilder obj = new StringBuilder();
		
		int k=gfg.length;
		System.out.println("size of string " + k);
		
		/*for(int i=0;i<k;i++)
		{
		
		obj.append(gfg[i]+ " ");
		
		
		}
		
		String str=obj.toString();
		System.out.println("string generated by tostring method id -->"+  str);*/
		
		for(int i=k-1;i>=0; i--)
		{
			obj.append(gfg[i]+ " ");
		}
			
		
		String str1=obj.toString();
		System.out.println("reverse string generated by tostring method id -->"+  str1);
		
		
		
	}

}
